# Generated by Django 5.1.4 on 2025-01-02 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_ressource_video_file_stripe'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripe',
            name='country',
            field=models.CharField(default='country', max_length=255),
        ),
        migrations.AddField(
            model_name='stripe',
            name='cvc',
            field=models.CharField(default='cvc', max_length=255),
        ),
        migrations.AddField(
            model_name='stripe',
            name='expiry',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='stripe',
            name='number_card',
            field=models.CharField(default='card', max_length=255),
        ),
        migrations.AddField(
            model_name='stripe',
            name='zip_code',
            field=models.CharField(default='0000', max_length=255),
        ),
    ]
