# Generated by Django 5.1.4 on 2025-01-02 22:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_stripe_country_stripe_cvc_stripe_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
