# Generated by Django 5.1.4 on 2025-01-03 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='ressources',
        ),
        migrations.AddField(
            model_name='ressource',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.lesson'),
        ),
    ]
